### ISSUE TITLE
Mongo can't insert the data

### ISSUE THREAD

**Issue by zhwenh** [zmap/celerybeat-mongo#17]
celery -A celtask.celeryapp --loglevel=info beat -S celerybeatmongo.schedulers.MongoScheduler
and show
oScheduler
celery beat v3.1.20 (Cipater) is starting.
__    -    ... __   -        _
Configuration ->
    . broker -> redis://10.1.245.138:6379/9
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celerybeatmongo.schedulers.MongoScheduler

    . logfile -> [stderr]@%INFO
    . maxinterval -> now (0s)
[2016-03-08 20:05:35,197: INFO/MainProcess] beat: Starting...
[2016-03-08 20:05:35,197: INFO/MainProcess] backend scheduler using mongodb://10.1.245.138:27017/celery:schedules

**but Mongo db：celery  table：schedules  can't insert the data  it‘s none**
celtask/celeryapp.py 
CELERY_MONGODB_SCHEDULER_DB = "celery",
    CELERY_MONGODB_SCHEDULER_COLLECTION = "schedules",
    CELERY_MONGODB_SCHEDULER_URL = "mongodb://10.1.245.138:27017",
    CELERYBEAT_SCHEDULE={
        "test_xsum": {
            "task": "celtask.tasks.mul",
            "schedule": timedelta(seconds=10),
            "args": (2,3)
        },
         "test_crontab": {
            # ececutes every monday morning at 7:30
            "task": "celtask.tasks.add",
            "schedule": timedelta(seconds=10),
            "args": (2,3)
        }

celtask/tasks.py
from __future__ import absolute_import
import time
from celtask.celeryapp import app

@app.task
def add(x, y):
    time.sleep(5)
    return x + y

@app.task
def mul(x, y):
    time.sleep(10)
    return x * y

**Comment by zakird** [comment]
I'm not sure I understand the issue. The schedule is going to be defined in Mongo---not in the python code. The library doesn't handle putting schedules into the library for you---it's expected that the models are present and then the scheduler will read them. If you want to add them, you can use the models with MongoEngine.
