### ISSUE TITLE
TypeError: Keyword must be String

### ISSUE THREAD

**Issue by aayush06** [zmap/celerybeat-mongo#32]
Hi 
Following is my code:
```
from celery import Celery

app = Celery('tasks', broker='redis://localhost')

app.config_from_object('celeryconfig')

@app.task
def add(x, y):
    return int(x) + int(y)
```
and following is snippet of mongo collection

`{
	"_id" : ObjectId("59786aa52f3dd74f7a2943d3"),
	"_cls" : "PeriodicTask",
	"name" : "Addition",
	"task" : "task.add",
	"enabled" : true,
	"interval" : {
		"every" : 1,
		"period" : "minute"
	},
	"args" : [
		"2",
		"5"
	],
	"kwargs" : {
		"max_targets" : "100"
	}
}
`

and when i am executing command:
celery beat -l debug -S  celerybeatmongo.schedulers.MongoScheduler
it shows following error:
(![image](https://user-images.githubusercontent.com/10773612/28616382-2a57cf2a-721a-11e7-9a56-c0272ffeede9.png))

**Comment by rafaelreuber** [comment]
Your collection is wrong.
Execute to following update to fix:

```
db.schedules.update({_id: ObjectId("59786aa52f3dd74f7a2943d3")}, { $set: {interval: {"_cls": "Interval", "every" : 1, "period" : "minutes"}}})
db.schedules.update({_id: ObjectId("59786aa52f3dd74f7a2943d3")}, { $unset: {"period": ""}})
```

I used to following version to reproduce your issue:
python 3.4
celery 4.3
celerybeat-mongo: 0.2
mongoengine: 0.20.0

**Comment by rafaelreuber** [comment]
Hey @zakird, I think this issue could be closed.
