### ISSUE TITLE
Enabled tasks do not run when there is another schedule entry which is disabled

### ISSUE THREAD

**Issue by carocaro12** [zmap/celerybeat-mongo#37]
Hello!

I'm using celery 4.2.1 and celerybeat-mongo 0.1.0. In the tests I'm doing, I have 2 tasks:

**Task A:** disabled, Interval schedule (runs every hour)
**Task B:** enabled, Interval schedule (runs every 30 seconds)

The problem I have is that Task B executes only once.

Celery's heap of schedule entries is ordered primarily by time, because it is a queue of tuples defined in https://github.com/celery/celery/blob/4.1/celery/beat.py (_'time', 'priority', 'entry'_), and it doesn't take into account the enabled flag.
The _next_time_to_run_ of Task A is always 5 seconds (because the task is disabled -> celerybeatmongo/schedulers.py - line 58).
After Task B runs for the first time, its _next_time_to_run_ is 30 seconds.
Therefore, Task A ends up being at the top of the heap always, even though it is disabled.
This means that Task B never makes it to the top of the heap again and the _Scheduler.tick()_ method never checks if Task B is due.

I'm looking for suggestions on how to fix this (considering that the definition of the _event_t_ tuple is in Celery) or corrections to my analysis.

Thanks you very much for your help!

**Comment by bchiavarini** [comment]
Hello!
i have encountered the same problem about disabled schedules that blocks the execution of enabled one using celery and celerybeat-mongo.
Do you have managed to fix it in some way?

Thanks for your help!

**Comment by carocaro12** [comment]
Hi,

I fixed it by overriding the _MongoScheduleEntry.editable_fields_equal_ method in celerybeat-mongo to also compare the _enabled_ flag:
    
    from celerybeatmongo.schedulers import MongoScheduleEntry as _MongoScheduleEntry
    
    class MongoScheduleEntry(_MongoScheduleEntry):

    def __init__(self, task):
        self.enabled = task.enabled
        super(MongoScheduleEntry, self).__init__(task)

    def editable_fields_equal(self, other):
        if getattr(self, 'enabled') != getattr(other, 'enabled'):
            return False
        return super().editable_fields_equal(other)

I hope that helps!

**Comment by rafaelreuber** [comment]
I'm having the same problem. This is blocker bug.
