### ISSUE TITLE
Tasks are added in batches, here we need to filter the dormant tasks

### ISSUE THREAD

**Issue by binyoucai** [zmap/celerybeat-mongo#44]
https://github.com/zmap/celerybeat-mongo/blob/5b4287e07d84c016110ef98da0294d082a0b1f2f/celerybeatmongo/schedulers.py#L157

    def get_from_database(self):
        self.sync()
        d = {}
        for doc in self.Model.objects():
            if doc.enabled:  
                d[doc.name] = self.Entry(doc)
        return d

**Comment by rafaelreuber** [comment]
I think you are right. Are you facing some specific problem? If yes, could add more details about this?

**Comment by binyoucai** [comment]
Well, I added some scheduled tasks, and then modified one of the tasks in the database to enabled = true, and then all tasks were not executed.

**Comment by rafaelreuber** [comment]
This is the some problem on #37

**Comment by rafaelreuber** [comment]
Hi @binyoucai. This bug is fixed on this [fork](https://github.com/rafaelreuber/celerybeat-mongo/tree/development). Please install this development version and check if works for you.

```shell
pip install https://github.com/rafaelreuber/celerybeat-mongo/archive/development.zip --upgrade
```

**Comment by binyoucai** [comment]
ok,ok

**Comment by rafaelreuber** [comment]
Hi @binyoucai "ok,ok" means your problem is solved? :)
