### ISSUE TITLE
All tasks execution stops when one task hits it's "max_run_count" value

### ISSUE THREAD

**Issue by P-T-I** [zmap/celerybeat-mongo#55]
I'm just starting testing celerybeat-mongo and it looks quite promising, however when I've got two tasks:

- one enabled task with no "max_run_count" (call it alive)
- one enabled task with "max_run_count" == "total_run_count" (call it dead)

Both tasks are crontab tasks with a crontab setting for executing every 1 minute.
 
When starting the celery beat deamon the first task get executed (as expected), and the second isn't (as expected). However After that first exectution everything freezes; the first task is not executed after the crontab cycle expires.

Restarting the celery beat deamon repeats this proces. 

Looks like still alive tasks are blocked when there is a dead task in the database.

**Comment by P-T-I** [comment]
adjusting the get_from_database method to:
```
    def get_from_database(self):
        self.sync()
        d = {}
        for doc in self.Model.objects().filter(enabled=True):
            if doc.max_run_count == 0 or doc.max_run_count > doc.total_run_count:
                d[doc.name] = self.Entry(doc)
        return d
```

appears to fix this behavior

**Comment by rafaelreuber** [comment]
How the scheduler entries was created? Did you used the celerybeat-mongo models or inserted in mongodb directly?

**Comment by P-T-I** [comment]
Inserted into mongodb directly. I used the document example from the repo README, added it into the database twice and added the "max_run_count" field in one document.

**Comment by rafaelreuber** [comment]
I just reproduced this issue with interval scheduler.

**Comment by P-T-I** [comment]
ok; for what it is worth, I was using the crontab example.

**Comment by rafaelreuber** [comment]
Please check [this fork](https://github.com/rafaelreuber/celerybeat-mongo/tree/development) this solved you problem:

```python
pip install https://github.com/rafaelreuber/celerybeat-mongo/archive/development.zip --upgrade
```

**Comment by P-T-I** [comment]
I checked your commit; I can confirm it has solved my problem. Will it be pushed to master and/or new release?

**Comment by rafaelreuber** [comment]
I think it'll a new release will be published. After this PR, two critical bugs it fixed on master but isn't available in pypi.org. It deserves an 0.2.1 :)

**Comment by P-T-I** [comment]
I agree, looking forward to the new release!
